default:
  tags:
    - led-weltkarte
  before_script:
    - . /opt/esp/activate_idf_v6.0.sh

variables:
  TIDY_ESP_FLAGS: "--target=xtensa-esp32s3-elf -D__xtensa__ -DCONFIG_IDF_TARGET_ESP32S3"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - web-checks
  - build
  - clang-checks
  - test
  - deploy

# Info zu Ausführung:
# Falls Push auf main + Änderungen in Software/
# Falls MR an main + Änderungen in Software/

web-lint-check:
  stage: web-checks
  script: 
    - echo "Checking website formatting rules"
    - cd "$CI_PROJECT_DIR/Software/web"
    - npm i
    - npm run lint
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Software/web/**/*
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - Software/**/*
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always

generate-certificate:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN! - Generating certificate"
    - $(git rev-parse --show-toplevel)/Software/components/https_server/certs/generate.sh
  artifacts:
    paths:
      - Software/components/https_server/certs/server_cert.pem
      - Software/components/https_server/certs/server_key.pem
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Software/**/*
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - Software/**/*
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always

build-job-preact:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN! - Building preact"
    - cd "$CI_PROJECT_DIR/Software/web" 
    - npm i
    - npm run build
  artifacts:
    paths:
      - Software/components/https_server/www/
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Software/**/*
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - Software/**/*
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always

build-job-idf:
  stage: build
  needs: ["build-job-preact", "generate-certificate"]
  script:
    - echo "Building project with ESP-IDF"
    - cd "$CI_PROJECT_DIR/Software" && idf.py -C apps/led_wall_master -B apps/led_wall_master/build build
  artifacts:
    paths:
      - Software/apps/led_wall_master/build/
      - Software/apps/led_wall_master/sdkconfig
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Software/**/*
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - Software/**/*
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always

clang-format-check:
  stage: clang-checks
  script:
    - echo "Checking formating rules"
    - cd "$CI_PROJECT_DIR/Software"
    - git ls-files '*.c' '*.cpp' '*.h' '*.hpp' | xargs clang-format --dry-run --Werror
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Software/**/*
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - Software/**/*
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always

# Wir müssen die toolchain zu clang ändern für eine funktionierende build_commands.json
# Um systemheader zu ignoriern muss mit sed alle -I/system.. header durch -isystem/system.. umbenannt werden
# Am Ende werden warnings.txt durchsucht um bei Fehlern die Pipeline abzubrschen - clang-tidy lieft exit 0 auch 
# bei fehlern in checks
clang-tidy-check:
  stage: clang-checks
  variables:
    IDF_TOOLCHAIN: "clang"
  script:
    - echo "Running clang-tidy"
    - cd "$CI_PROJECT_DIR/Software"
    - ./run_clang_tidy.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Software/**/*
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - Software/**/*
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always

test-on-esp:
  stage: test
  script:
    - echo "Run pytests for Hardware tests"
    - cd "$CI_PROJECT_DIR/Software" && /usr/local/bin/esp-lock /dev/ttyACM0 bash -c "cd apps/led_wall_master && pytest ../../pytest/*.py --embedded-services esp,idf --target esp32s3"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Software/**/*
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - Software/**/*
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
  timeout: 10m # spätestens nach 10 Minuten usb port wieder freigeben!

test-without-target:
  stage: test
  script:
    - echo "Tests without need to connect to USB"
    - cd "$CI_PROJECT_DIR/Software"
    - mkdir -p unittest/build_unit
    - echo "Building and running unit tests..."
    - ./run_unit_tests.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Software/**/*
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - Software/**/*
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
      
# If the deployed will become the actual flashed there are for security reasons some changes necessary: 
# - The private key is currently included in the build folder for flashing but this should not be the case if this is the actually used private key (the private key should only be stored on the esp)
deploy-prod:
  stage: deploy
  script:
    - echo "Deploy..."
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Software/**/*
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - Software/**/*
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
#  environment: production
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Nur auf main
#      when: manual                             
#    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH # Mauell auch von andren Branches
#      when: manual
