#include "webserver.hpp"
#include "embedded_files.hpp" // Autogenerated file gets created with configuration of idf project
#include "https_server.hpp"
#include <esp_log.h>

esp_err_t Webserver::embedded_file_get_handler(httpd_req_t *req) {
	auto *file_data = static_cast<embed_file_data *>(req->user_ctx);

	ESP_LOGD(kTag, "Requested route method=%s fd=%d uri=%s", HttpsServer::http_method_to_str(static_cast<httpd_method_t>(req->method)),
			 httpd_req_to_sockfd(req), static_cast<const char *>(req->uri));

	// Set the content type of the response to the type of the file
	esp_err_t err = httpd_resp_set_type(req, file_data->file_content_type);
	if (err != ESP_OK) {
		ESP_LOGE(kTag, "Failed to set the content type for the response");
		return err;
	}

	// Send the file as response
	// NOLINTNEXTLINE(cppcoreguidelines-pro-type-reinterpret-cast)
	err = httpd_resp_send(req, reinterpret_cast<const char *>(file_data->file_start), static_cast<ssize_t>(file_data->file_size));
	if (err != ESP_OK) {
		ESP_LOGE(kTag, "Failed to set the content for the response");
		return err;
	}

	return ESP_OK;
}

// NOLINTNEXTLINE(cppcoreguidelines-interfaces-global-init)
embed_file_data Webserver::app_js_data{
	.file_start = &app_js_start[0], .file_end = &app_js_end[0], .file_size = app_js_size, .file_content_type = "application/javascript"};

// NOLINTNEXTLINE(cppcoreguidelines-interfaces-global-init)
embed_file_data Webserver::index_css_data{
	.file_start = &index_css_start[0], .file_end = &index_css_end[0], .file_size = index_css_size, .file_content_type = "text/css"};

// NOLINTNEXTLINE(cppcoreguidelines-interfaces-global-init)
embed_file_data Webserver::worldmap_svg_data{
	.file_start = &worldmap_svg_start[0], .file_end = &worldmap_svg_end[0], .file_size = worldmap_svg_size, .file_content_type = "image/svg+xml"};

// NOLINTNEXTLINE(cppcoreguidelines-interfaces-global-init)
embed_file_data Webserver::index_html_data{
	.file_start = &index_html_start[0], .file_end = &index_html_end[0], .file_size = index_html_size, .file_content_type = "text/html"};

// NOLINTNEXTLINE(cppcoreguidelines-interfaces-global-init)
embed_file_data Webserver::vite_svg_data{
	.file_start = &vite_svg_start[0], .file_end = &vite_svg_end[0], .file_size = vite_svg_size, .file_content_type = "image/svg+xml"};
