[req]
default_bits = 2048
prompt = no
default_md = sha256
distinguished_name = req_distinguished_name
x509_extensions = v3_req

[req_distinguished_name]
C = DE
ST = Baden-Wuerttemberg
L = Ulm
O = Light wall
CN = light-wall

[v3_req]
basicConstraints = CA:FALSE
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = light-wall.local
# Required only for remote access
DNS.2 = localhost