#include "routes.hpp"
#include "embedded_files.hpp" // Autogenerated file gets created with configuration of idf project
#include <esp_check.h>
#include <esp_log.h>

static const char *TAG = "webserver-routes";

struct embed_file_data {
	const unsigned char *file_start;
	const unsigned char *file_end;
	const size_t file_size;
	const char *file_content_type;
};

/**
 * GET Handler for files which are embedded into the ESPs memory
 *
 * @param req The request being responded to
 * @retval - `ESP_OK`: Succeed
 * @retval - `ESP_ERR_INVALID_ARG`: Null request pointer
 * @retval - `ESP_ERR_HTTPD_INVALID_REQ`: Invalid request pointer
 * @retval - `ESP_ERR_HTTPD_RESP_HDR`: Essential headers are too large for internal buffer
 * @retval - `ESP_ERR_HTTPD_RESP_SEND`: Error in raw send
 *
 * For more details, see:
 *
 * - [ESP-IDF HTTP Server Documentation](https://docs.espressif.com/projects/esp-idf/en/v6.0/esp32s3/api-reference/protocols/esp_http_server.html)
 *
 * - [ESP-IDF Embedding Binary
 * Documentation](https://docs.espressif.com/projects/esp-idf/en/v6.0/esp32s3/api-guides/build-system.html#embedding-binary-data)
 */
static esp_err_t embedded_file_get_handler(httpd_req_t *req) {
	embed_file_data *file_data = (embed_file_data *)req->user_ctx;

	ESP_LOGD(TAG, "Requested route: %s %s", http_method_to_str((httpd_method_t)req->method), req->uri);

	// Set the content type of the response to the type of the file
	ESP_RETURN_ON_ERROR(httpd_resp_set_type(req, file_data->file_content_type), TAG, "Failed to set the content type for the response");

	// Send the file as response
	ESP_RETURN_ON_ERROR(httpd_resp_send(req, (const char *)file_data->file_start, file_data->file_size), TAG,
						"Failed to set the content for the response");

	return ESP_OK;
}

static embed_file_data assets_app_js_data{
	.file_start = app_js_start,
	.file_end = app_js_end,
	.file_size = app_js_size,
	.file_content_type = "application/javascript",
};

static embed_file_data assets_index_css_data{
	.file_start = index_css_start,
	.file_end = index_css_end,
	.file_size = index_css_size,
	.file_content_type = "text/css",
};

static embed_file_data assets_worldmap_svg_data{
	.file_start = worldmap_svg_start,
	.file_end = worldmap_svg_end,
	.file_size = worldmap_svg_size,
	.file_content_type = "image/svg+xml",
};

static embed_file_data index_html_data{
	.file_start = index_html_start,
	.file_end = index_html_end,
	.file_size = index_html_size,
	.file_content_type = "text/html",
};

static embed_file_data vite_svg_data{
	.file_start = vite_svg_start,
	.file_end = vite_svg_end,
	.file_size = vite_svg_size,
	.file_content_type = "image/svg+xml",
};

/**
 * Configurations for routes
 *
 * First register the fixed assets routes and than register all remaining routes to point to the index.html and let it handle the rest. Routing is
 * than done by the browser including error pages.
 */
const size_t routes_size = 5;
static const httpd_uri_t routes[]{
	{.uri = "/assets/app.js", .method = HTTP_GET, .handler = embedded_file_get_handler, .user_ctx = (void *)&assets_app_js_data},
	{.uri = "/assets/index.css", .method = HTTP_GET, .handler = embedded_file_get_handler, .user_ctx = (void *)&assets_index_css_data},
	{.uri = "/assets/worldmap.svg", .method = HTTP_GET, .handler = embedded_file_get_handler, .user_ctx = (void *)&assets_worldmap_svg_data},
	{.uri = "/vite.svg", .method = HTTP_GET, .handler = embedded_file_get_handler, .user_ctx = (void *)&vite_svg_data},
	{.uri = "*", .method = HTTP_GET, .handler = embedded_file_get_handler, .user_ctx = (void *)&index_html_data},
};

/**
 * Registers a route and the handler for it
 *
 * @param handle handle to HTTPD server instance
 * @param uri_handler pointer to handler that needs to be registered
 * @retval - `ESP_OK`: Succeed
 * @retval - `ESP_ERR_INVALID_ARG`: Null arguments
 * @retval - `ESP_ERR_HTTPD_HANDLERS_FULL`: No slots left for new handler
 * @retval - `ESP_ERR_HTTPD_HANDLER_EXISTS`: Handler with same URI and method already registered
 *
 * For more details, see:
 *
 * - [ESP-IDF HTTP Server Documentation](https://docs.espressif.com/projects/esp-idf/en/v6.0/esp32s3/api-reference/protocols/esp_http_server.html)
 */
static esp_err_t register_route(httpd_handle_t handle, const httpd_uri_t *uri_handler) {
	esp_err_t ret = httpd_register_uri_handler(handle, uri_handler);
	if (ret == ESP_OK) {
		ESP_LOGI(TAG, "Registered route: %s %s", http_method_to_str(uri_handler->method), uri_handler->uri);
	} else {
		ESP_LOGE(TAG, "Failed to registered route: %s %s", http_method_to_str(uri_handler->method), uri_handler->uri);
	}
	return ret;
}

esp_err_t register_routes(httpd_handle_t handle) {
	for (size_t i = 0; i < routes_size; i++) {
		ESP_RETURN_ON_ERROR(register_route(handle, &routes[i]), TAG, "Failed to register route");
	}

	return ESP_OK;
}

constexpr const char *http_method_to_str(httpd_method_t method) {
	switch (method) {
	case HTTP_GET:
		return "GET";
	case HTTP_POST:
		return "POST";
	case HTTP_PUT:
		return "PUT";
	case HTTP_DELETE:
		return "DELETE";
	case HTTP_PATCH:
		return "PATCH";
	case HTTP_HEAD:
		return "HEAD";
	case HTTP_OPTIONS:
		return "OPTIONS";
	default:
		return "UNKNOWN";
	}
}
